import os
from openai import OpenAI
import json

class AIManager:
    """
    A unified interface to interact with Large Language Models (LLMs)
    for resume tailoring and job matching analysis.
    
    This class uses the OpenAI-compatible API standard, allowing it to easily
    switch between local models (e.g., via Ollama) or cloud providers 
    (e.g., Groq, Together AI) by simply changing the base_url and api_key.
    """

    def __init__(self, base_url: str, api_key: str = "no-key-needed", model_name: str = "meta-llama/llama-4-scout-17b-16e-instruct"):
        """
        Initializes the AIManager with the chosen LLM provider.

        Args:
            base_url (str): The endpoint URL for the API (e.g., 'http://localhost:11434/v1' for Ollama).
            api_key (str): The API key (defaults to 'no-key-needed' for local models).
            model_name (str): The specific model to use (e.g., 'llama3', 'mistral').
        """
        self.client = OpenAI(
            base_url=base_url,
            api_key=api_key
        )
        self.model_name = model_name

    def calculate_match_score(self, master_cv: str, job_description: str) -> str:
        """
        Analyzes a master resume against a job description to calculate a match score
        and suggest key areas for tailoring.

        Args:
            master_cv (str): The user's complete, unfiltered resume data.
            job_description (str): The target job's requirements and description.

        Returns:
            str: The LLM's structured response containing the score and insights.
        """
        
        # System prompt defines the AI's persona and strict rules.
        system_prompt = (
            "You are an expert IT Recruiter and Career Coach. "
            "Your task is to analyze a candidate's Master Resume against a Job Description. "
            "Provide a match score from 0 to 100%. Highlight strong matches and missing skills. "
            "Keep the answer strictly professional and concise."
        )

        # User prompt is the actual data we are feeding to the AI.
        user_prompt = f"Job Description:\n{job_description}\n\nCandidate Master CV:\n{master_cv}"

        try:
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.3 # Low temperature makes the AI more deterministic and less "creative/hallucinating"
            )
            return response.choices[0].message.content
            
        except Exception as e:
            return f"Error connecting to LLM: {str(e)}"
        
    def generate_master_cv(self, cv_texts: list[str]) -> str:
        """
        Merges multiple resume texts into a single, comprehensive Master CV.
        
        Args:
            cv_texts (list[str]): A list containing the raw text of different CV versions.
            
        Returns:
            str: The unified Master CV generated by the LLM.
        """
        system_prompt = (
            "You are an Expert Career Coach and IT Recruiter. "
            "I will provide you with text extracted from different versions of a candidate's resume (e.g., LinkedIn, Gupy, Standard PDF). "
            "Your task is to merge them into a single, highly professional 'Master CV'. "
            "Remove all redundancies, combine complementary information, and organize it clearly into standard sections: "
            "Professional Summary, Core Skills, Professional Experience, Education, and Languages. "
            "CRITICAL RULE: Keep the output strictly in the original language of the documents (Portuguese) and use a professional tone."
        )

        # Combine the texts with clear separators so the AI knows they are different documents
        combined_text = "\n\n--- NEXT CV VERSION ---\n\n".join(cv_texts)
        user_prompt = f"Here are the CV versions to merge:\n\n{combined_text}"

        try:
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.2 # Low temperature to ensure it merges accurately without hallucinating fake experiences
            )
            return response.choices[0].message.content
            
        except Exception as e:
            return f"Error generating Master CV: {str(e)}"
    def evaluate_job_match(self, master_cv: str, job_description: str) -> dict:
        """
        Compares the Master CV against a job description and returns a match score and rationale.
        
        Args:
            master_cv (str): The text of the candidate's master resume.
            job_description (str): The text of the job posting.
            
        Returns:
            dict: A dictionary containing 'score' (int) and 'rationale' (str).
        """
        system_prompt = (
            "You are an expert IT Recruiter and Career Coach. "
            "Your task is to evaluate a candidate's Master CV against a Job Description. "
            "Return ONLY a valid JSON object with two keys:\n"
            "1. 'score': An integer from 0 to 100 representing the candidate's compatibility with the job.\n"
            "2. 'rationale': A short paragraph (max 3 sentences) in Portuguese explaining the score. "
            "Highlight missing critical skills or strong matches. Do NOT use markdown formatting like ```json."
        )

        user_prompt = (
            f"--- MASTER CV ---\n{master_cv}\n\n"
            f"--- JOB DESCRIPTION ---\n{job_description}"
        )

        try:
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.1, # Very low temperature for analytical consistency
                response_format={"type": "json_object"} # Forces the LLM to return valid JSON
            )
            
            result_str = response.choices[0].message.content
            return json.loads(result_str)
            
        except Exception as e:
            print(f"❌ AI Evaluation Error: {str(e)}")
            return {"score": 0, "rationale": "Failed to generate evaluation."}

# Example of how to use this class locally (if you had Ollama installed)
if __name__ == "__main__":
    # Pointing to a local Ollama instance running on default port
    ai = AIManager(base_url="http://localhost:11434/v1", model_name="llama3")
    
    # Dummy data for testing
    dummy_cv = "Python developer with 3 years of experience. Knows Docker and PostgreSQL."
    dummy_job = "Looking for a Mid-level Python Engineer. Must know Docker, SQL, and AWS."
    
    # print(ai.calculate_match_score(dummy_cv, dummy_job))