import datetime
from sqlalchemy import Column, Integer, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from core.database import Base
from datetime import datetime, timezone

class Match(Base):
    """
    SQLAlchemy model representing the 'matches' table.
    Acts as a junction table connecting Jobs and Resumes, storing the AI's 
    evaluation score and analysis text.
    """
    __tablename__ = 'matches'
    
    id = Column(Integer, primary_key=True, index=True)
    
    # Foreign Keys linking to the exact Job and Resume
    job_id = Column(Integer, ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    resume_id = Column(Integer, ForeignKey("resumes.id", ondelete="CASCADE"), nullable=False)
    
    # The evaluation data generated by the LLM
    match_score = Column(Integer, nullable=True) # e.g., 85 (meaning 85%)
    ai_analysis = Column(Text, nullable=True)    # The bullet points generated by the AI
    
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    # Relationships to easily access the Job and Resume objects from a Match object
    job = relationship("Job")
    resume = relationship("Resume")